### ISSUE TITLE
Mapping not working in mixxx 2.3.5

### ISSUE THREAD

**Issue by didgewind** [illusori/mixxx-behringer-cmdstudio2a#1]
Hi, I copied the three files to mixxx controllers folder, pluged my controller, selected Behringer CMD Studio 2a (Enchanced) preset... and nothing is working. No knob, no wheel, no fader... nothing.

I have another controller (nanoKontrol2) that I mapped long ago with an old mixxx version and this is working normally, so it's not software issue.

Could you confirm everything is fine with 2.3.5, or should I change something?

Thanks.

**Comment by didgewind** [comment]
Ok, I found the issue. It's with my controller, it's sending midi signals through channel 4, and the mappings are on channel 1. I'll change the mappings in the file, I think that will be enough.

Tx.

**Comment by illusori** [comment]
Ah, I haven't tested it with any controller other than the Behringer CMD studio 2A, it's highly likely to break in other ways because most controllers send their own midi codes for each control, so you'll probably need to remap more than just the channels.

A lot of the control scheme is quite specific to making use of things in a way that makes sense for the physical layout of the 2A's buttons too, so I'm not sure how useful that will be over the default controls you can get with just Mixxx on its own.

If it's useful to you though then great, glad it's of help!
